apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: devops-java-lab
    newName: pavandevp12/devops-java-lab
    newTag: "22"
  
patches:
  - path: service.yaml